from selenium import webdriver
qspider=webdriver.Chrome()
qspider.get("https://www.facebook.com/")
qspider.maximize_window()
qspider.implicitly_wait(30)
# qspider.find_element_byssxwsx_id("email").send_keys("radha23041993@gmail.com")
# qspider.find_element_by_id("pass").send_keys("lilyc")
# qspider.find_element_by_id("u_0_b").click()
# qspider.find_element_by_xpath("//input[@name='firstname']").send_keys("janvi")
# qspider.find_element_by_xpath("//input[@name='lastname']").send_keys("gupta")
# qspider.find_element_by_xpath("//input[@id='u_0_o']").send_keys("987678987")
# qspider.find_element_by_xpath("//input[@data-type='password']").send_keys("70898788")
# qspider.find_element_by_xpath("//input[@id='u_0_9']").click()
# qspider.find_element_by_xpath("//input[@id='u_0_a']]").click()
qspider.find_element_by_xpath("//span[text()='Create an account']").click()
qspider.find_element_by_xpath("//div[contains(text(),'Facebook helps you ')]").click()